FROM quay.io/signalfuse/collectd:latest

# Disable everything we can except elasticsearch
ENV COLLECTD_INTERVAL=3 COLLECTD_HOSTNAME=solr-test DISABLE_AGGREGATION=true DISABLE_CPU=true DISABLE_CPUFREQ=true DISABLE_DF=true DISABLE_DISK=true DISABLE_DOCKER=true DISABLE_HOST_MONITORING=true DISABLE_INTERFACE=true DISABLE_LOAD=true DISABLE_MEMORY=true DISABLE_PROTOCOLS=true DISABLE_VMEM=true DISABLE_UPTIME=true

# Debian is super minimalistic
RUN apt-get update &&\
    apt-get install -yq netcat curl

## The context of the image build should be the root dir of this repo!!
ADD integration-test/setup_openstack /.docker/setup_openstack
CMD /.docker/setup_openstack

RUN python -m pip install -U pip==20.3.4

ADD requirements-python2.txt /opt/collectd-openstack/requirements.txt
RUN python -m pip install -r /opt/collectd-openstack/requirements.txt

ADD *.py /opt/collectd-openstack/
ADD integration-test/10-openstack-test.conf /etc/collectd/managed_config/
