version: '2'
services:
  collectd:
    build:
      context: ..
      dockerfile: integration-test/Dockerfile.collectd
    environment:
      SF_API_TOKEN: testing
      SF_INGEST_HOST: fake_sfx
    depends_on:
      - fake_sfx
      - devstack
      - devstack-init

  devstack:
    image: devstack
    container_name: devstack
    # required for systemd
    privileged: true
    volumes:
      - /lib/modules:/lib/modules:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    ports:
      - "8090:80"
    environment:
      container: docker
    command: /lib/systemd/systemd

  devstack-init:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: "docker exec devstack systemctl start devstack"
    depends_on:
      - devstack

  fake_sfx:
    build:
      context: .
      dockerfile: Dockerfile.sink

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - collectd

